#!/usr/bin/env bash
# Configure domain zone so subdomain www points to ur load-balancer IP
fetch_domain_info () {
    domain="$1"
    subdomain="$2"
    result=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $result" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ $# -eq 1 ]; then
    domain="$1"
    fetch_domain_info "$domain" "www"
    fetch_domain_info "$domain" "lb-01"
    fetch_domain_info "$domain" "web-01"
    fetch_domain_info "$domain" "web-02"
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    fetch_domain_info "$domain" "$subdomain"
fi
