#!/usr/bin/env bash
# Configure domain zone so subdomain www points to ur load-balancer IP
fetch_domain_info() {
    domain="$1"
    subdomain="$2"
    result=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$result" | awk '/IN/ {print $4}')
    ip_address=$(echo "$result" | awk '/IN/ {print $5}')
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${ip_address}"
}
if [ $# -eq 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        fetch_domain_info "$domain" "$sub"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    fetch_domain_info "$domain" "$subdomain"
fi
