#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page
# Contains the string Ceci n'est pas une page
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "/listen 80 default_server;/a error_page 404 /custom_404.html;" /etc/nginx/sites-enabled/default
sudo service nginx restart
