#!/usr/bin/env bash
# Configure Nginx so its HTTP resp has custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo service nginx restart
