#!/usr/bin/env bash
# Configure Nginx so its HTTP resp has custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "/server_name _;/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
