#!/usr/bin/env bash
# Configure and install HAproxy on your lb-01 server.
sudo apt-get update -y
sudo apt-get install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
WEB01_IP="35.174.176.33"
WEB02_IP="54.152.129.84"
sudo tee /etc/haproxy/haproxy.cfg <<EOF
global
    log 127.0.0.1 local0
    log 127.0.0.1 local1 notice
    maxconn 2000
    user haproxy
    group haproxy
    daemon

defaults
    mode http
    log global
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000ms
    timeout client 30000ms
    timeout server 30000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 ${WEB01_IP}:80 check
    server web02 ${WEB02_IP}:80 check
EOF
sudo systemctl enable haproxy
sudo systemctl restart haproxy
LOAD_BALANCER_IP="18.235.255.29"
curl -Is http://$LOAD_BALANCER_IP | grep "X-Served-By"
