#!/usr/bin/env bash
# Configure and install HAproxy on your lb-01 server.
sudo apt-get update -y
sudo apt-get install -y haproxy
WEB01_IP="35.174.176.33"
WEB02_IP="54.152.129.84"
sudo tee /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    pidfile /var/run/haproxy.pid
    maxconn 4096
    user haproxy
    group haproxy
    daemon
defaults
    mode http
    log global
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 ${WEB01_IP}:80 check
    server web02 ${WEB02_IP}:80 check
EOF
sudo systemctl enable haproxy
sudo systemctl start haproxy
LOAD_BALANCER_IP="your_load_balancer_ip"
curl -Is http://$LOAD_BALANCER_IP | grep "X-Served-By"
