#!/usr/bin/env bash
# Displays IP address passes as an argument
if [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ip_address="$1"

echo "PING $ip_address"
ping -c 5 "$ip_address"
