#!/usr/bin/env bash
# Configures to listening on port 80 of all the server’s active IPv4 IPs
# Nginx must be running
cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
service nginx restart
