#!/usr/bin/env bash
# Script with start, restart, stop
pid_file="/var/run/my_process.pid"
script_path="./manage_my_process"

start_process() 
{
	$script_path &
	echo $! > $pid_file
	echo "manage_my_process started"
}

stop_process()
{
	if [ -e $pid_file ]; then
		pid=$(cat $pid_file)
        	kill "$pid"
       		rm -f $pid_file
    		echo "manage_my_process stopped"
  	fi
}

restart_process()
{
	stop_process
	start_process
	echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
