#!/usr/bin/env bash
# Displays message with a sleep of 2 seconds then msg when SIGTERM signal is received
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
