#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd
if [ ! -f "/etc/passwd" ]; then
	exit 1
fi
while IFS=: read -r username password userid groupid userdesc homedir shell; do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd
