#!/usr/bin/env bash
# This script displays content of the current directory in list format
for file in *; do
	if [[ $file != .* ]]; then
		after_dash=$(echo "$file" | cut -d'-' -f2-)
		echo "$after_dash"
	fi
done
