#!/usr/bin/env bash
# script that configures an Ubuntu server localhost resolves to 127.0.0.2 facebook.com resolves to 8.8.8.8
sudo cp /etc/hosts /etc/hosts.backup
sudo sed -i 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/ s/.*/8.8.8.8 facebook.com/' /etc/hosts
cat /etc/hosts
echo "To revert changes, run: sudo cp /etc/hosts.backup /etc/hosts"
sudo service systemd-resolved restart
